apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: local
  namespace: garden-local
spec:
  seedName: local
  cloudProfileName: local
  secretBindingName: local
  region: local
  networking:
    type: local
  provider:
    type: local
    workers:
    - machine:
        type: local
      cri:
        name: containerd
      name: local
      maximum: 1
      minimum: 1
      maxSurge: 1
      maxUnavailable: 0
  kubernetes:
    version: 1.21.0
