apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: garden
commonLabels:
  app: etcd

secretGenerator:
- name: etcd-tls
  files:
  - client-ca.crt
  - tls.crt
  - tls.key

resources:
- service.yaml
- statefulset.yaml
