apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: seed-local
  namespace: garden
  files:
  - kubeconfig

resources:
- project.yaml
- secret-internal-domain.yaml
- secret-default-domain.yaml
- cloudprofile.yaml
- controller-registration.yaml
- seed.yaml
- secretbinding.yaml
