apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- project.yaml
- secret-internal-domain.yaml
- secret-default-domain.yaml
- cloudprofile.yaml
- controller-registration.yaml
- secretbinding.yaml
