apiVersion: v1
kind: Secret
metadata:
  name: local
  namespace: garden-local
type: Opaque
# usually we would put cloud provider credentials into this secret, but it isn't needed for provider-local as no such
# credentials exist. Hence, we just create an empty secret
---
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  name: local
  namespace: garden-local
secretRef:
  name: local
