apiVersion: core.gardener.cloud/v1beta1
kind: Seed
metadata:
  name: local
spec:
  provider:
    type: local
    region: local
  secretRef:
   name: seed-local
   namespace: garden
  dns:
    ingressDomain: local.seed.local.gardener.cloud
  networks:
    nodes: 172.19.0.0/16
    pods: 10.1.0.0/16
    services: 10.2.0.0/16
    shootDefaults:
      pods: 10.3.0.0/16
      services: 10.4.0.0/16
  settings:
    excessCapacityReservation:
      enabled: false
    scheduling:
      visible: true
    shootDNS:
      enabled: true
    verticalPodAutoscaler:
      enabled: true
